[package]
name = "linestring"
version = "0.4.0"
authors = ["eadf"]
edition = "2018"
description = "2d and 3d polylines"
readme = "README.md"
repository = "https://github.com/eadf/linestring.rs"
license = "AGPL-3.0"
keywords = ["geometry", "intersection", "douglas-peucker", "visvalingam-whyatt", "convex-hull"]

[features]
impl-cgmath = ["cgmath"]
impl-nalgebra = ["nalgebra"]
impl-mint = ["mint"]
impl-vecmath = ["vecmath"]
impl-vec = []
impl-rayon = ["rayon"]
# used for debugging purposes
console_trace = []
# everything is enabled by default, or else rust doc wont find anything
# i.e. disable all features except mint with this dependency:
#  [dependencies]
#  linestring = {version="^0.0.10",default-features=false,features=["impl-mint"]}
default = ["impl-cgmath", "impl-nalgebra", "impl-mint", "impl-vecmath", "impl-vec", "impl-rayon"]

[dependencies]
cgmath = { version = "0.18", optional=true }
nalgebra = { version = ">=0.24,<0.27", optional=true }
mint = { version = "0.5", optional = true }
vecmath = { version = "1.0", optional = true }
rayon = { version = "1.5", optional = true }
num-traits = "0.2"
approx = "0.4"
ahash = "0.7"
thiserror = "1.0"
itertools = "0.10"
yabf = "0.1"

[[example]]
name = "fltk_gui"
path = "example/fltk_gui.rs"
required-features = ["impl-cgmath"]

[dev-dependencies]
fltk = "1.0"
cgmath = "0.18"
rand = "0.8"
rand_chacha = "0.3"
criterion = "0.3"

[[bench]]
name = "intersection_bench"
harness = false

[[bench]]
name = "simplify_bench"
harness = false