[package]
name = "linestring"
version = "0.0.7"
authors = ["eadf"]
edition = "2018"
description = "2d and 3d polylines"
readme = "README.md"
repository = "https://github.com/eadf/linestring.rs"
license = "AGPL-3.0"
keywords = ["geometry", "intersection", "douglas-peucker", "visvalingam-whyatt"]

[features]
impl-cgmath = ["cgmath"]
impl-nalgebra = ["nalgebra"]
impl-mint = ["mint"]
impl-vecmath = ["vecmath"]
impl-vec = []
# used for debugging purposes
console_trace = []

[dependencies]
cgmath = { version = "^0.18.0", optional = true }
nalgebra = { version = "^0.24.1", optional = true }
mint = { version = "^0.5.6", optional = true }
vecmath = { version = "^1.0.0", optional = true }
num-traits = "^0.2.14"
approx = "^0.4.0"
fnv = "^1.0.7"
rb_tree = "^0.3.3"
thiserror = "^1.0.23"
ordered-float = "^2.1.1"
itertools = "^0.10.0"

[[example]]
name = "fltk_gui"
path = "example/fltk_gui.rs"

[dev-dependencies]
fltk = "^0.15.1"
cgmath = "^0.18.0"
