[package]
name = "linestring"
version = "0.0.4"
authors = ["eadf"]
edition = "2018"
description = "Work in progress"
readme = "README.md"
repository = "https://github.com/eadf/linestring.rs"
license = "AGPL-3.0"
keywords = ["geometry", "intersection", "douglas-peucker", "visvalingam-whyatt"]

[features]
impl-cgmath = ["cgmath"]
impl-nalgebra = ["nalgebra"]
impl-mint = ["mint"]
impl-vec = []

[dependencies]
cgmath = { version = "^0.18.0", optional = true }
nalgebra = { version = "^0.24.1", optional = true }
mint = { version = "^0.5.6", optional = true }
num-traits = "^0.2.14"
approx = "^0.4.0"
thiserror = "^1.0.23"

[[example]]
name = "fltk_gui"
path = "example/fltk_gui.rs"

[dev-dependencies]
fltk = "^0.14.2"
itertools = "^0.10.0"
cgmath = "^0.18.0"
