[package]
name = "linestring"
version = "0.0.1"
authors = ["eadf"]
edition = "2018"
description = "Work in progress"
readme = "README.md"
repository = "https://github.com/eadf/linestring.rs"
license = "AGPL-3.0"
keywords = ["geometry", "douglas-peucker", "visvalingam-whyatt"]

[features]
default = ["std"]
#default = ["std", "impl-cgmath", "mint", "impl-nalgebra"]
impl-cgmath = ["cgmath"]
#impl-glam = ["glam"]
impl-nalgebra = ["nalgebra"]
impl-mint = ["mint"]
std = []

[dependencies]
cgmath = { version = "^0.18.0", optional = true }
#glam = { version = "0.10", optional = true }
nalgebra = { version = "^0.24.1", optional = true }
mint = { version = "^0.5.6", optional = true }
