[package]
name = "linestring"
version = "0.7.0"
authors = ["eadf"]
edition = "2018"
description = "2d and 3d polylines"
readme = "README.md"
repository = "https://github.com/eadf/linestring.rs"
license = "AGPL-3.0"
keywords = ["geometry", "intersection", "douglas-peucker", "visvalingam-whyatt", "convex-hull"]

[features]
# used for debugging purposes
console_trace = []

[dependencies]
cgmath = { version = "0.18" }
rayon = { version = "1.5", optional = true }
# we always use this approx, despite cgmath exporting it's own version
approx = "0.5"
num-traits = "0.2"
ahash = "0.7"
thiserror = "1.0"
itertools = "0.10"
yabf = "0.2"

[[example]]
name = "fltk_gui"
path = "example/fltk_gui.rs"

[build-dependencies]
version_check = "0.9"

[dev-dependencies]
fltk = "1.1"
rand = "0.8"
rand_chacha = "0.3"
criterion = "0.3"

[[bench]]
name = "intersection_bench"
harness = false

[[bench]]
name = "simplify_bench"
harness = false

[profile.release]
lto = true

[badges]
maintenance = { status = "actively-developed" }