[package]
name = "linestring"
version = "0.0.2"
authors = ["eadf"]
edition = "2018"
description = "Work in progress"
readme = "README.md"
repository = "https://github.com/eadf/linestring.rs"
license = "AGPL-3.0"
keywords = ["geometry", "douglas-peucker", "visvalingam-whyatt"]

[features]
default = ["std"]
impl-cgmath = ["cgmath"]
impl-nalgebra = ["nalgebra"]
impl-mint = ["mint"]
std = []

[dependencies]
cgmath = { version = "^0.18.0", optional = true }
nalgebra = { version = "^0.24.1", optional = true }
mint = { version = "^0.5.6", optional = true }
num-traits = "^0.2.14"
approx = "^0.4.0"
