[package]
name = "linestring"
version = "0.6.2"
authors = ["eadf"]
edition = "2018"
description = "2d and 3d polylines"
readme = "README.md"
repository = "https://github.com/eadf/linestring.rs"
license = "AGPL-3.0"
keywords = ["geometry", "intersection", "douglas-peucker", "visvalingam-whyatt", "convex-hull"]

[features]
# Enables a plain old vector [] implementation
vector = []
# used for debugging purposes
console_trace = []
# everything is enabled by default, or else rust doc wont find anything
# E.g. to disable all features except mint you use this line:
#  linestring = {version="0.5",default-features=false,features=["mint"]}
default = ["cgmath", "nalgebra", "mint", "vecmath", "vector", "rayon"]

[dependencies]
cgmath = { version = "0.18", optional = true }
nalgebra = { version = "0.28", optional = true }
mint = { version = "0.5", optional = true }
vecmath = { version = "1.0", optional = true }
rayon = { version = "1.5", optional = true }
# we always use this approx, despite cgmath exporting it's own version
approx = "0.5"
num-traits = "0.2"
ahash = "0.7"
thiserror = "1.0"
itertools = "0.10"
yabf = "0.2"

[[example]]
name = "fltk_gui"
path = "example/fltk_gui.rs"
required-features = ["cgmath"]

[build-dependencies]
version_check = "0.9"

[dev-dependencies]
fltk = "1.1"
cgmath = "0.18"
rand = "0.8"
rand_chacha = "0.3"
criterion = "0.3"

[[bench]]
name = "intersection_bench"
harness = false

[[bench]]
name = "simplify_bench"
harness = false

[profile.release]
lto = true

[badges]
maintenance = { status = "actively-developed" }