name: Clippy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install stable
        run : rustup toolchain install stable --component rustfmt,clippy --allow-downgrade
      - name: Run clippy
        run: cargo +stable clippy
